# CodeRabbit Configuration for TCU-2K25-DASHBOARD
# Dashboard de Estudos TCU TI 2025
# React 19.2 + TypeScript + Vite + Node.js + Express + SQLite

language: "pt-BR"
early_access: false
enable_free_tier: true

reviews:
  # Review configuration
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  poem: false
  review_status: true
  collapse_walkthrough: false
  sequence_diagrams: false
  changed_files_summary: true
  labeling_instructions: []

  # Auto-review triggers
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT REVIEW"
      - "DRAFT"

    drafts: false
    base_branches:
      - main
      - develop

  # Paths to include/exclude
  path_filters:
    - "!node_modules/**"
    - "!dist/**"
    - "!build/**"
    - "!coverage/**"
    - "!*.min.js"
    - "!*.min.css"
    - "!package-lock.json"
    - "!yarn.lock"
    - "!pnpm-lock.yaml"
    - "!components/ui/**"  # shadcn/ui generated components
    - "!.env*"
    - "!*.log"
    - "!sqlite_data/**"

  path_instructions:
    - path: "**/*.tsx"
      instructions: |
        - Verifique se os componentes React seguem as melhores práticas
        - Garanta que hooks sejam usados corretamente
        - Verifique se há problemas de performance (re-renders desnecessários)
        - Confirme que componentes são tipados corretamente com TypeScript
        - Verifique acessibilidade (a11y) em elementos interativos

    - path: "**/*.ts"
      instructions: |
        - Verifique tipagem TypeScript rigorosa
        - Garanta que interfaces e types estejam bem definidos
        - Verifique tratamento de erros com try-catch
        - Confirme que funções async usem await corretamente

    - path: "contexts/*.tsx"
      instructions: |
        - Verifique se o Context API está sendo usado eficientemente
        - Garanta que não há problemas de performance com re-renders
        - Confirme que os providers estão otimizados com useMemo/useCallback quando necessário
        - Verifique se as atualizações de estado são otimistas onde apropriado

    - path: "server/**/*.js"
      instructions: |
        - Verifique segurança de endpoints (validação de entrada, sanitização)
        - Confirme tratamento adequado de erros
        - Verifique se queries SQL estão protegidas contra injection
        - Garanta que respostas HTTP usem status codes corretos

    - path: "services/*.ts"
      instructions: |
        - Verifique tratamento de erros em chamadas API
        - Confirme que há fallbacks apropriados (ex: localStorage)
        - Verifique se API keys não estão expostas em logs
        - Garanta que requisições assíncronas sejam tratadas corretamente

    - path: "Dockerfile"
      instructions: |
        - Verifique boas práticas de segurança Docker
        - Confirme multi-stage builds quando apropriado
        - Verifique se imagens base são oficiais e atualizadas

    - path: "docker-compose.yml"
      instructions: |
        - Verifique configuração de volumes persistentes
        - Confirme que portas estão mapeadas corretamente
        - Verifique se variáveis de ambiente são usadas apropriadamente

# Knowledge Base - Documentação do projeto
chat:
  auto_reply: true

knowledge_base:
  # Estrutura do projeto
  learnings:
    - pattern: "import.*from.*@/"
      content: "O projeto usa alias @/ que resolve para a raiz do projeto (não há diretório src/)"

    - pattern: "ProgressoContext|useProgresso"
      content: |
        O ProgressoContext gerencia o estado de progresso com:
        - completedItems: Set<string> para IDs de itens completados
        - Persistência via SQLite API com fallback para localStorage
        - Atualizações otimistas (UI atualiza imediatamente, DB sincroniza em background)

    - pattern: "gemini|GEMINI_API_KEY"
      content: |
        Integração com Google Gemini API (modelo gemini-2.5-flash):
        - API key exposta no bundle (desenvolvimento apenas)
        - Usa grounded search para informações atualizadas
        - Otimizado para contexto de concurso TCU

    - pattern: "edital|Materia|Topic|Subtopic"
      content: |
        Modelo de dados hierárquico:
        - Edital → Materia[] → Topic[] → Subtopic[] (recursivo)
        - IDs únicos (ex: "1.2.3") para cada item
        - Apenas leaf nodes (sem subtópicos) são rastreados no progresso

    - pattern: "database|sqlite|progress"
      content: |
        API de progresso (Express + SQLite):
        - GET /api/progress - retorna IDs completados
        - POST /api/progress - adiciona IDs (body: {ids: string[]})
        - DELETE /api/progress - remove IDs (body: {ids: string[]})
        - Fallback para localStorage se API indisponível

# Custom prompts for reviews
tone_instructions: |
  - Seja construtivo e educativo nas revisões
  - Priorize segurança, performance e manutenibilidade
  - Sugira melhorias específicas com exemplos de código quando relevante
  - Seja conciso mas completo nas explicações
  - Use português brasileiro (pt-BR)

# Security and quality checks
checks:
  # Security checks
  - name: "API Key Exposure"
    description: "Verificar se API keys ou secrets estão sendo commitados"
    pattern: "(GEMINI_API_KEY|API_KEY|SECRET|PASSWORD|TOKEN)\\s*=\\s*['\"]\\w+"
    severity: "error"
    files:
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.js"
    exclude:
      - "**/*.example.*"
      - "**/*.template.*"

  - name: "Console Logs"
    description: "Verificar console.log esquecidos (exceto console.error)"
    pattern: "console\\.(log|debug|info)\\("
    severity: "warning"
    files:
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.js"
    exclude:
      - "**/*.test.*"
      - "vite.config.ts"

  - name: "SQL Injection Risk"
    description: "Verificar queries SQL que concatenam strings diretamente"
    pattern: "db\\.(run|all|get)\\([`'\"].*\\$\\{.*\\}.*[`'\"]"
    severity: "error"
    files:
      - "server/**/*.js"

  - name: "TODO Comments"
    description: "Rastrear TODOs e FIXMEs no código"
    pattern: "(TODO|FIXME|HACK|XXX):"
    severity: "info"
    files:
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.js"

  - name: "Hardcoded URLs"
    description: "Verificar URLs hardcoded que deveriam usar variáveis de ambiente"
    pattern: "(http://localhost|https://localhost):\\d+"
    severity: "warning"
    files:
      - "services/**/*.ts"
    exclude:
      - "**/*.test.*"
      - "vite.config.ts"

# Tools configuration
tools:
  shellcheck:
    enabled: true

  eslint:
    enabled: true

  biome:
    enabled: true

  ruff:
    enabled: false  # Python não usado no projeto

  markdownlint:
    enabled: true

  github-checks:
    enabled: true
    timeout: 30

# Pre-merge checks
pre_merge_checks:
  - name: "React Best Practices"
    description: "Verificar boas práticas React (hooks, performance)"
    instructions: |
      - Hooks devem seguir as Rules of Hooks
      - useEffect deve ter array de dependências correto
      - Componentes pesados devem usar React.memo quando apropriado
      - Event handlers devem usar useCallback quando passados como props
    mode: "warning"

  - name: "TypeScript Strict"
    description: "Verificar tipagem rigorosa TypeScript"
    instructions: |
      - Evitar uso de 'any' sem justificativa
      - Interfaces devem estar bem definidas
      - Funções devem ter tipos de retorno explícitos quando não óbvio
      - Usar tipos ao invés de interfaces quando apropriado
    mode: "warning"

  - name: "Security Check"
    description: "Verificar questões de segurança críticas"
    instructions: |
      - Nenhuma API key ou secret commitado
      - Queries SQL usando prepared statements
      - Inputs de usuário devem ser validados/sanitizados
      - CORS configurado apropriadamente no backend
    mode: "error"

  - name: "Docker Best Practices"
    description: "Verificar boas práticas Docker quando arquivos Docker são modificados"
    instructions: |
      - Usar imagens base oficiais e minimalistas
      - Multi-stage builds quando apropriado
      - .dockerignore configurado corretamente
      - Expor apenas portas necessárias
    mode: "warning"

# Bot behavior
abort_on_close: true
